apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::687102289161:user/Kuber
      username: Kuber
      groups:
        - system:Kuber_group
